### ISSUE TITLE
Review Bouke

### ISSUE THREAD

**Issue by bgrevelt** [bgrevelt/PT_MA1_3#2]
Hi Alex, these are my review comments
- I would make the test report a little less concise (I know what that means now) maybe add a couple of lines explaining why you have decided to test the way you do. And for each test case why you have added that test case. What is the specific property you want to test with that specific test case (f.i. 'normal' parsing, ignoring white spaces, etc)
- I believe all of your failing test cases are actually rightly failing.
  -- All parsed data will come out of the parser in the form [<something>]
  -- "1 ==> 3" and "1<==>3" is actually invalid code (good negative test case). From the code I gather that implication and equivalence should be written with parentheses: "(1 ==> 3)" and "(1<==>3")
- Maybe you can add some more complex test cases like implication and/ or equivalence in conjunction / disjunction or stuff like that. The best thing would be to think of some systematic way to test.

**Comment by alexvanmanen** [comment]
Hi Bouke,

Thanks for your comments. I've processed your feedback. I've made the test report less concise. I've added comment what I test with each test case and also added extra tests case for implication and equivalence. Feel free to add more testcase or change the code if this improves it.
