### ISSUE TITLE
Review FormClassification.hs by Alex

### ISSUE THREAD

**Issue by alexvanmanen** [bgrevelt/PT_MA1_3#3]
Dear Bouke,

You've written a nice piece of code. Esspecially the tests. I think I noticed one small mistake and I've one improvement you could consider to take into account: 
1. Small error - (line: 43-45) You're defining equivalences tests and you add an implications test to it. It seems like an small mistake, but maybe I'm wrong
2. Improvement suggestion - You could test more equivalence laws. These laws can be found on page 46 in the Haskell Road to Logic book.

All by all I think this code is very nice.

Cheers, Alex

**Comment by alexvanmanen** [comment]
Hi Bouke,

I've got an extra minor improvement for your code. You could put some extra spaces or tabs when printing the test reults to the console. See code below:

testForm :: [(Form)] -> (Form -> Bool) -> Bool -> IO ()
testForm [] _ _ = do print ("Done")
testForm (frm: fs) f e = 
  if (f frm == e) 
    then do 
      print ("Test passed on: " ++ show frm)
      testForm fs f e
    else error ("failed test on: " ++ show frm)

-- One takes pairs of formulas, a classification function for  two 
-- formulas and an expected outcome of applyin the function to the two 
-- formulas
testFormRel :: [(Form,Form)] -> (Form -> Form -> Bool) -> Bool -> IO ()
testFormRel [] _ _ = do print ("Done")
testFormRel ((frm1,frm2): frmPairs) f e = 
  if (f frm1 frm2 == e) 
    then do 
      print ("Test passed on: " ++ show frm1 ++ "       "++ show frm2)
      testFormRel frmPairs f e
    else error ("failed test on: " ++ show frm1 ++ "       "++ show frm2)

**Comment by alexvanmanen** [comment]
Thanks for your work Bouke. You've written a nice piece of code.

**Comment by bgrevelt** [comment]
Hi Alex, thanks for the review.

I think the test you mention at (1) is correct. The test do no necessarily test functions which have an equivalence in them, they test if two functions are equivalent. In this case p -> q and -q -> -p  are equivalent:
p | q | p-> q| -q -> -p
0 | 0 |   1    |      1
0 | 1 |   1    |      1
1 | 0 |   0    |      0
1 | 1 |   1    |      1

(2) That' a good idea, thanks

(3) Yep, you're right, the layout of the test messages can be improved. I'll do that too.
