### ISSUE TITLE
Review FormulaGenerator.hs by Alex

### ISSUE THREAD

**Issue by alexvanmanen** [bgrevelt/PT_MA1_3#4]
Hi Jack,

Here is my feedback of your code:
- I'm missing the following items: time spent, formula generator and test report.
- Next to that I notice that the Test.QuickCheck is not in the master branch.
- Last but not least. I see The code below in Lecture.hs (line 124 - 135) gives 9 errors (Not in scope: ‘<$>’). The function Arbitrary is being used in ToyQuickCheck.hs. I think you added but I'm not sure, because I overwritten a part of the commit history, when I did my merge this afternoon (19 September 2015)

instance Arbitrary Form where
  arbitrary = sized $ \n ->
    oneof $
      [ Prop <$> arbitrary ]
      ++ if n == 0
         then [] -- No recursion at size 0
         else resize (n - 1) <$>
           [ Neg <$> arbitrary
           , Cnj <$> arbitrary
           , Dsj <$> arbitrary
           , Impl <$> arbitrary <_> arbitrary
           , Equiv <$> arbitrary <_> arbitrary ]

**Comment by Futsy** [comment]
Has been added by now!
